SchoolManagementSystems/Controllers/InventoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Entity;
using System.Data.Entity;

namespace SchoolManagementSystems.Controllers
{
    [HandleError]
    [SchoolManagementSystems.MvcApplication.SessionExpire]
    public class InventoryController : Controller
    {
        SchoolMgmtSysEntities db = new SchoolMgmtSysEntities();
        #region Category master
        public ActionResult Category(string Search_Data)
        {
            Categoryviewmodel _cvm = new Categoryviewmodel();
            FillPermission(21);
            if (Search_Data == null || Search_Data == "")
                _cvm._categorylist = db.sp_getcategory().OrderBy(m => m.catid).ToList();
            else
                _cvm._categorylist = db.sp_getcategory().Where(x => x.catname.ToUpper().Contains(Search_Data.ToUpper()) ||
                                                        x.status.ToUpper().Contains(Search_Data.ToUpper()) ||
                                                        x.catid.ToString().Contains(Search_Data.ToUpper())).OrderBy(m => m.catid).ToList();
            
            return View(_cvm);
        }
        public JsonResult FillCategoryDetails(int catid)
        {
            var data = db.tbl_category.Where(m => m.catid == catid).FirstOrDefault();
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        public JsonResult check_duplicate_category(string catname)
        {
            var data = db.tbl_category.Where(m => m.catname == catname).FirstOrDefault();
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        public ActionResult DMLCategory(int catid, string catname, bool status, string evt, int id)
        {
            Categoryviewmodel _cvm = new Categoryviewmodel();
            if (evt == "submit")
            {
                //db.sp_position_DML(_cvm.catid, _cvm.catname, _cvm.status, _cvm.academicyear, "").ToString();
                db.sp_category_DML(catid, catname, status, "").ToString();
            }
            else if (evt == "Delete")
            {
                //db.sp_position_DML(id, _cvm.catname, _cvm.status, _cvm.academicyear, "del").ToString();
                db.sp_category_DML(id, _cvm.catname, _cvm.status, "del").ToString();
            }
            _cvm._categorylist = db.sp_getcategory().ToList();
            return PartialView("_categoryList", _cvm);
        }
        #endregion

        public ActionResult Product(string Search_Data)
        {
            Categoryviewmodel _cvm = new Categoryviewmodel();
            FillPermission(23);
            _cvm.Categorylist = db.tbl_category.Where(x => x.status == true).ToList();
            _cvm._subCategorylist = db.tbl_SubCategory.Where(x => x.status == true).ToList();
            _cvm._vendorlist = db.tbl_InventoryVendor.Where(x => x.IsActive == true).ToList();
            if (Search_Data == null || Search_Data == "")
                _cvm._Productlist = db.sp_getProduct().OrderBy(m => m.Productid).ToList();
            else
                _cvm._Productlist = db.sp_getProduct().Where(x => x.Categoryid.ToUpper().Contains(Search_Data.ToUpper()) ||
                                                        x.status.ToUpper().Contains(Search_Data.ToUpper()) ||
                                                        x.Product.ToUpper().Contains(Search_Data.ToUpper()) ||
                                                        x.Productid.ToString().Contains(Search_Data.ToUpper())).OrderBy(m => m.Productid).ToList();
            
            return View(_cvm);
        }

        public ActionResult DMLProduct(int Productid, int catid, int subcatid, string Product, bool status,int vendorid, string evt, int id)
        {
            Categoryviewmodel _cvm = new Categoryviewmodel();
            if (evt == "submit")
            {
                //db.sp_position_DML(_cvm.catid, _cvm.catname, _cvm.status, _cvm.academicyear, "").ToString();
                db.sp_Product_DML(Productid, catid, subcatid, Product, status, "",vendorid).ToString();
            }
            else if (evt == "Delete")
            {
                //db.sp_position_DML(id, _cvm.catname, _cvm.status, _cvm.academicyear, "del").ToString();
                db.sp_Product_DML(id, catid, subcatid, Product, status, "del", vendorid).ToString();
            }
            _cvm._Productlist = db.sp_getProduct().ToList();
            _cvm._vendorlist = db.tbl_InventoryVendor.Where(x => x.IsActive == true).ToList();
            return PartialView("_Productlist", _cvm);
        }

        public JsonResult check_duplicate_Product(string Product, int Categoryid)
        {
            string pro = Product;
            int catid = Categoryid;
            var data = db.tbl_Product.Where(x => x.Product == pro && x.Categoryid == catid).FirstOrDefault();
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public JsonResult FillProductDetails(int productid)
        {
            var data = db.tbl_Product.Where(m => m.Productid == productid).FirstOrDefault();
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Inventory(string Search_Data)
        {
            Categoryviewmodel _cvm = new Categoryviewmodel();
            FillPermission(24);
            _cvm.Categorylist = db.tbl_category.Where(x => x.status == true).ToList();
            _cvm._subCategorylist = new List<tbl_SubCategory>();
            _cvm.productlist = new List<tbl_Product>();
            if (Search_Data == null || Search_Data == "")
                _cvm._Inventorylist = db.sp_getInventory().OrderBy(m => m.Inventoryid).ToList();
            else
                _cvm._Inventorylist = db.sp_getInventory().Where(x => x.catname.ToUpper().Contains(Search_Data.ToUpper()) ||
                                                        x.Price.ToString().Contains(Search_Data.ToUpper()) ||
                                                        x.Product.ToUpper().Contains(Search_Data.ToUpper()) ||
                                                        x.Inventoryid.ToString().Contains(Search_Data.ToUpper()) ||
                                                        x.Quantity.ToString().Contains(Search_Data.ToUpper())).OrderBy(m => m.Inventoryid).ToList();
            
            return View(_cvm);
        }

        public JsonResult BindProduct(int categoryid, int subcategoryid)
        {
            var data = db.tbl_Product.Where(m => m.Categoryid == categoryid && m.SubCategoryid == (subcategoryid == 0 ? m.SubCategoryid : subcategoryid) && m.Status == true);
            return Json(new SelectList(data, "Productid", "Product"));
        }

        public JsonResult BindSubCategory(int categoryid)
        {
            var data = db.tbl_SubCategory.Where(m => m.Categoryid == categoryid && m.status == true);
            return Json(new SelectList(data, "SubCategoryid", "SubCategoryname"));
        }

        public ActionResult DMLInventory(string evt, int id, string price, string Qty, int Prodid)
        {
            Categoryviewmodel _cvm = new Categoryviewmodel();
            if (evt == "submit")
            {
                //db.sp_position_DML(_cvm.catid, _cvm.catname, _cvm.status, _cvm.academicyear, "").ToString();
                db.sp_Inventory_DML(Prodid, Convert.ToInt32(Qty), Convert.ToDecimal(price), id, "").ToString();
            }
            else if (evt == "Delete")
            {
                //db.sp_position_DML(id, _cvm.catname, _cvm.status, _cvm.academicyear, "del").ToString();
                db.sp_Inventory_DML(Prodid, Convert.ToInt32(Qty), Convert.ToDecimal(price), id, "del").ToString();
            }
            _cvm._Inventorylist = db.sp_getInventory().ToList();
            return PartialView("_Inventorylist", _cvm);
        }

        public JsonResult check_duplicate_Inventory(int Productid)
        {
            int pro = Productid;
            var data = db.tbl_Inventory.Where(x => x.Productid == pro).FirstOrDefault();
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public JsonResult FillInventoryDetails(int inventoryid)
        {
            var data = (from a in db.tbl_Inventory
                        join e in db.tbl_Product on a.Productid equals e.Productid
                        from d in db.tbl_SubCategory.Where(dt => dt.Categoryid == e.Categoryid).DefaultIfEmpty()
                        select new { a.Inventoryid, a.Productid, a.Quantity, a.Price, e.Categoryid, SubCategoryid = d.SubCategoryid.ToString() == null ? 0 : d.SubCategoryid }).FirstOrDefault();
            return Json(data, JsonRequestBehavior.AllowGet);
        }


        #region SubCategory master
        public ActionResult SubCategory(string Search_Data)
        {
            Categoryviewmodel _cvm = new Categoryviewmodel();
            FillPermission(22);
            _cvm._categorylist = db.sp_getcategory().ToList();
            if (Search_Data == null || Search_Data == "")
                _cvm._SubCategorylist = db.sp_getSubCategory().OrderBy(m => m.SubCategoryid).ToList();
            else
                _cvm._SubCategorylist = db.sp_getSubCategory().Where(x => x.catname.ToUpper().Contains(Search_Data.ToUpper()) ||
                                                        x.status.ToUpper().Contains(Search_Data.ToUpper()) ||
                                                        x.SubCategoryname.ToUpper().Contains(Search_Data.ToUpper()) ||
                                                        x.SubCategoryid.ToString().Contains(Search_Data.ToUpper())).OrderBy(m => m.SubCategoryid).ToList();
            
            return View(_cvm);
        }
        public JsonResult FillSubCategoryDetails(int catid)
        {
            var data = db.tbl_SubCategory.Where(m => m.SubCategoryid == catid).FirstOrDefault();
            return Json(data, JsonRequestBehavior.AllowGet);
        }

SchoolManagementSystems/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Entity;
using Common;

namespace SchoolManagementSystems.Controllers
{
    [HandleError]
    public class LoginController : Controller
    {
        SchoolMgmtSysEntities db = new SchoolMgmtSysEntities();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Login(string Username, string Password)
        {
            ViewData["Error"] = "";
            Userviewmodel uvm = new Userviewmodel();
            Dashboardviewmodel dvm = new Dashboardviewmodel();
            Dashboardviewmodel.MyProfileView mpv = new Dashboardviewmodel.MyProfileView();
            string currentdate = CommonUtility.FormatedDateString(DateTime.Now);
            string datemonth = currentdate.Substring(0, 5);
            if (Session["Userid"] != null && Session["Userid"].ToString() != "")
            {
                dvm.Newsdatacollection = db.tbl_news.Where(m => m.Status == true).ToList();
                dvm.BirthdaylistDetails = db.sp_GetBirthdayListDetails().Where(m => m.DOB.ToUpper().Contains(datemonth.ToString())).OrderBy(m => m.Studnm).ToList();

                if (Convert.ToString(Session["Role"]) == "1")
                { return View("../MyProfile/Index", mpv); }
                else { return View("DashBoard", dvm); }
            }
            else
            {
                try
                {
                    uvm.Userdatacollection = db.tbl_user.Where(m => m.UserName == Username && m.Password == Password && m.Status == 1).ToList();
                }
                catch { }
                if (uvm.Userdatacollection != null)
                {
                    if (uvm.Userdatacollection.Count() > 0 && uvm.Userdatacollection[0].Status == 1)
                    {
                        Session["Userid"] = uvm.Userdatacollection[0].Userid.ToString();
                        Session["User"] = uvm.Userdatacollection[0].UserName.ToString();
                        Session["Role"] = uvm.Userdatacollection[0].Type.ToString();
                        Session["Genid"] = uvm.Userdatacollection[0].Genid.ToString();
                        dvm.Newsdatacollection = db.tbl_news.Where(m => m.Status == true).ToList();
                        dvm.BirthdaylistDetails = db.sp_GetBirthdayListDetails().Where(m => m.DOB.ToUpper().Contains(datemonth.ToString())).OrderBy(m => m.Studnm).ToList();
                        if (Convert.ToString(Session["Role"]) == "1")
                        { return View("../MyProfile/Index", mpv); }
                        else { return View("DashBoard", dvm); }
                       
                    }
                    else
                    {
                        ViewData["Error"] = "Either UserName or Password is incorrect / You are not active User!..";
                        return View("Index");
                    }
                }
               
                return View("Index");
            }
        }

        public ActionResult Logout()
        {
            Session.Clear();
            return View("Index");
        }

        public ActionResult ChangePassword()
        {
            Userviewmodel uvm = new Userviewmodel();
            return View(uvm);
        }

        [HttpGet]
        public JsonResult UpdatePassword(int Userid, string OldPassword, string NewPassword)
        {
            Userviewmodel uvm = new Userviewmodel(); string msg = null;
            uvm.checkpassword = db.sp_changepassword(Userid, NewPassword, OldPassword, "check").ToList();
            if (uvm.checkpassword.Count > 0)
            {
                db.sp_changepassword(Userid, NewPassword, OldPassword, "change");
                msg = "Password changed successfully!..";
            }
            else
            {
                msg = "Old password entered is incorrect!..";
            }
            //ViewData["msg"] = msg;
            //return View(ViewData["msg"]);
            return Json(uvm, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult ForgotPassword()
        {
            Userviewmodel uvm = new Userviewmodel();
            return View(uvm);
        }

        public ActionResult GetPassword()
        {
            Userviewmodel uvm = new Userviewmodel();
            return View(uvm);
        }

        public void FillPermission(int modid)
        {
            var per = db.sp_get_permission(Convert.ToInt32(Session["Role"]), modid).ToList();
            for (int i = 0; i < per.Count; i++)
            {
                if (per[i].Permissionid == 1) { ViewData["Add"] = "Allow"; }
                else if (per[i].Permissionid == 2) { ViewData["Modify"] = "Allow"; }
                else if (per[i].Permissionid == 3) { ViewData["View"] = "Allow"; }
                else if (per[i].Permissionid == 4) { ViewData["Delete"] = "Allow"; }
            }
        }

        public ActionResult GetNews(Dashboardviewmodel dash)
        {

            return View("Dashboard");
        }


    }
}

SchoolManagementSystems/Views/Inventory/Category.cshtml
@model Entity.Categoryviewmodel
@{
    ViewBag.Title = "Category";
    Layout = "~/Views/shared/_SharedLayout.cshtml";
}
<script type="text/javascript">
    $(document).ready(function () {
        FillPermission();
        $("#status").prop('checked', true);
        $("#lblmsg").text('');
        $('#categoryid input').attr("readonly", true);
        if ($("#catid").val() == "0") {
            $("#categoryid").hide();
        }

        $("#result").on("click", ".btn_edit", function (evt) {
            var catid = this.id;
            $.ajax({
                type: 'GET',
                url: '@Url.Action("FillCategoryDetails")',
                dataType: 'JSON',
                data: { catid: catid },
                success: function (data) {
                    $("#categoryid").show();
                    $('#categoryid input').val(data.catid);
                    $("#catname").val(data.catname);
                    $("#status").prop('checked', data.status);
                }
            });
        });

        function clear() {
            $("#categoryid").hide();
            $('#categoryid input').val('0');
            $("#catname").val('');
            
        }
        function clearmsg() {
            $("#msg").hide();
            $("#msgs").hide();
        }

        $('#catname').blur(function () {
            var catname = $('#catname').val();
            $.ajax({
                type: 'GET',
                url: '@Url.Action("check_duplicate_category")',
                dataType: 'JSON',
                data: { catname: catname },
                success: function (data) {
                    clearmsg();
                    if (data.catname != null) {
                        $("#msg").show();
                        $("#lblmsg").text("Category Name Already Exists!..");
                        $("#lblmsg").css({ "color": "orange" });
                        $("#lblmsg").css({ "font-size": "15px" });
                        $('#catname').val('');
                        return false;
                    }
                }
            });
        });

        $("#insert").click(function () {
            validations();
            var remark = "false";
            if ($("#status").is(":checked")) {
                remark = "true";
            }
            $.ajax({
                type: 'POST',
                url: '@Url.Action("DMLCategory")',
                data: { catid: $('#categoryid input').val(), catname: $('#catname').val(), status: remark, evt: 'submit', id: 0 },
                success: function (result) {
                    $("#msgs").show();
                    $("#lblmsgs").text("Category updated successfully!..");
                    $("#lblmsgs").css({ "color": "green" });
                    $("#lblmsgs").css({ "font-size": "15px" });
                    $("#result").html(result);
                    clear();
                    ReloadPaging();
                }
            });
        });

        $("#reset").click(function () {
            clear();
            clearmsg();
        });

        $("#result").on("click", ".btn_delete", function (evt) {
            var catid = this.id;
            var flag = confirm('Are you sure you want to delete this Category?');
            if (flag) {
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("DMLCategory")',
                    data: $('#frm').serialize() + "&evt=Delete&id=" + catid + "",
                    success: function (result) {
                        $("#msgs").show();
                        $("#lblmsgs").text("Category deleted successfully!..");
                        $("#lblmsgs").css({ "color": "orange" });
                        $("#lblmsgs").css({ "font-size": "15px" });
                        $("#result").html(result);
                        clear();
                        ReloadPaging();
                    }
                });
            }
        });

        function validations() {
            var cnt = 0;

            if ($("#catname").val() == '') {
                cnt++;
                $("#catname").css({
                    "border": "2px solid red"
                });
            }
            else {
                $("#catname").css({
                    "border": "",
                    "background": ""
                });
            }

            if (cnt != 0)
                e.preventDefault();
        }
        ReloadPaging();
    });
</script>
@Html.HiddenFor(m => m.catid)
@Html.Partial("_PermissionHiddenFlds")
<div class="container-fluid-full">
             
		<div class="row-fluid">
                  @Html.Partial("_InventorySubMenu")
	<div id="content" class="span10">
        	<div class="row-fluid">
             
                    <ul class="breadcrumb">
                     <li><i class="icon-home"></i>@Html.ActionLink("Home", "Login", "Login")<i class="icon-angle-right"></i>
                      @Html.ActionLink("Inventory Management", "Category", "Inventory", "")<i class="icon-angle-right"></i></li>
                        <li class="active">Category Master</li>
                        @*<div style="float: right;">
                            @using (Html.BeginForm())
                            {

                                @Html.TextBox("Search_Data", ViewBag.FilterValue as string)
                                <input type="submit" value="Find" />
                            }
                        </div>*@
                    </ul>
                <div class="panel-body">
                    <div id="msg" hidden="hidden" class="alert alert-warning" visible="false">
                        <strong><label id="lblmsg"></label></strong>
                    </div>
                    <div id="msgs" hidden="hidden" class="alert alert-success" visible="false">
                        <strong><label id="lblmsgs"></label></strong>
                    </div>
                </div>

                       <div class="row-fluid sortable">
              <div class="box span12">
					<div class="box-header" data-original-title>
						<h2><i class="fa fa-edit"></i><span class="break"></span>Form Elements</h2>
						<div class="box-icon">
						
							<a href="#" class="btn-minimize"><i class="fa fa-chevron-up" aria-hidden="true"></i></a>
						
						</div>
					</div>
                               		<div class="box-content">
						<form id="frm" class="form-horizontal">
                              
						
                                  <fieldset>
                                        @using (Html.BeginForm("", "", FormMethod.Post, new { id = "frm", @class="form-horizontal" }))
                                        {
                                            @Html.ValidationSummary(true)
                                            <div id="lblmsg"  class="control-group">
                                            </div>
                                            <div id="categoryid"  class="control-group">
                                                @Html.LabelFor(model => model.catid, new {@class = "control-label" })
                                                  <div class="controls"> 
                                                @Html.EditorFor(model => model.catid, new { @class = "col-md-5 form-control form_in" })
                                                @Html.ValidationMessageFor(model => model.catid)
                                                      </div>
                                            </div>
                                            <div  class="control-group">
                                                @Html.LabelFor(model => model.catname, new {@class = "control-label" })
                                                  <div class="controls"> 
                                                @Html.EditorFor(model => model.catname, new { @class = "col-md-5 form-control form_in" })
                                                @Html.ValidationMessageFor(model => model.catname)
                                                      </div>
                                            </div>
                                            <div  class="control-group">
                                                @Html.LabelFor(model => model.status, new {@class = "control-label" })
                                                  <div class="controls"> 
                                                @Html.CheckBoxFor(model => model.status, new { @class = "col-md-5 form-control form_in" })
                                                @Html.ValidationMessageFor(model => model.status)
                                                      </div>
                                            </div>
                                            <div class="form-actions">
                                                <input type="button" class="btn btn-primary" id="insert" value="Submit" />
                                                <input type="button" class="btn btn-primary" id="reset" value="Reset" />
                                            </div>
                                        }
                                  </fieldset>
                                </form>
					
					</div>
				</div><!--/span-->
			
			</div><!--/row-->
                   <div class="row-fluid sortable">
              <div class="box span12">
                  	<div class="box-header" data-original-title>
						<h2><i class="fa fa-edit"></i><span class="break"></span>Form Elements</h2>
						<div class="box-icon">
						
							<a href="#" class="btn-minimize"><i class="fa fa-chevron-up" aria-hidden="true"></i></a>
						
						</div>
					</div> 
                  <div class="box-content">
                                                @Html.Partial("_categoryList")
                                         </div>
                  </div>
                                             
                                                

                                         </div>
        </div>
             
    </div>
</div>
   
            </div>

SchoolManagementSystems/Views/Inventory/Stock_Report.cshtml
@model Entity.Categoryviewmodel
@{
    ViewBag.Title = "Category";
    Layout = "~/Views/shared/_SharedLayout.cshtml";
}
<div class="container">
    <div class="row">
        <div class="col-md-12" style="padding-top: 75px;margin-bottom: 90px;">
            <ul class="breadcrumb">
                <li>@Html.ActionLink("Home", "Login", "Login")</li>
                <li>@Html.ActionLink("Inventory Management", "Category", "Inventory", "")</li>
                <li class="active">Stock Report</li>
            </ul>
        </div>
        <div class="col-md-2">
            <div class="well blbg">
                <a href="~/Login/Login">Back to Home</a>
                @Html.Partial("_InventorySubMenu")
            </div>
        </div>
        <div class="col-md-9">
            <center>
                <table width="100%">
                    <tr>
                        <td>
                            <div>
                                <div class="well blbg" style="">
                                    @Html.Partial("_stockreport")
                                </div>
                            </div>
                        </td>
                    </tr>
                </table>
            </center>
        </div>
        <!-- table end -->
        @*</div>*@
    </div>
</div>

SchoolManagementSystems/Views/Inventory/_Inventorylist.cshtml
@model Entity.Categoryviewmodel
<div id="result" class="table-responsive">
    <table class="table table-striped table-bordered bootstrap-datatable datatable">
     <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Inventoryid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.catname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Product)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>

            <th class="edt">
                @Html.DisplayName("Action")
            </th>
        </tr></thead>
        <tbody>
        @foreach (var item in Model._Inventorylist)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Inventoryid)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.catname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Product)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>

                <td>
                    <input type="button" id="@item.Inventoryid" class="btn btn-default btn_edit" value="Edit" />
                    @*<input type="button" id="@item.Inventoryid" class="btn btn-default btn_delete" value="Delete" />*@
                </td>
            </tr>
        } </tbody>
    </table>
</div>

SchoolManagementSystems/Views/Inventory/_Productlist.cshtml
@model Entity.Categoryviewmodel
<div id="result" class="table-responsive">
    <table class="table table-striped table-bordered bootstrap-datatable datatable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Productid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.catname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.subcatname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Product)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VendorId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.status)
            </th>

            <th class="edt">
                @Html.DisplayName("Action")
            </th>
        </tr></thead>
        <tbody>
        @foreach (var item in Model._Productlist)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Productid)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Categoryid)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SubCategoryid)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Product)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.VendorName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.status)
                </td>

                <td>
                    <input type="button" id="@item.Productid" class="btn btn-default btn_edit" value="Edit" />
                    @*<input type="button" id="@item.Productid" class="btn btn-default btn_delete" value="Delete" />*@
                </td>
            </tr>
        }</tbody>
    </table>
</div>

SchoolManagementSystems/Views/Inventory/_stockreport.cshtml
@model Entity.Stockviewmodel
<div id="result" class="table-responsive">
    <table class="table tb-parshav">
    <tr>        
        <th>
            <span class="sptext">@Html.DisplayNameFor(model => model.catname)</span>
        </th> 
        <th>
            <span class="sptext">@Html.DisplayNameFor(model => model.Product)</span>
        </th>        
        <th>
            <span class="sptext">@Html.DisplayNameFor(model => model.totalstock)</span>
        </th>        
        <th>
            <span class="sptext">@Html.DisplayNameFor(model => model.usedstock)</span>
        </th>        
        <th>
            <span class="sptext">@Html.DisplayNameFor(model => model.remainingstock)</span>
        </th>        
    </tr>
    @foreach (var item in Model._stocklist)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.catname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Product)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.totalstock)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.usedstock)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.remainingstock)
            </td>
        </tr>
    }
</table>
</div>