SchoolManagementSystems/Controllers/LibraryController.cs
using Entity;
using SchoolManagementSystems.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using Common;
using System.Data.SqlClient;

namespace SchoolManagementSystems.Controllers
{
    public class LibraryController : Controller
    {
        //
        // GET: /Library/
            SchoolMgmtSysEntities db = new SchoolMgmtSysEntities();


       
        public ActionResult Index(libBookentry lb)
        {
            //FillPermission(47);
            lb._authorlist = db.tbl_lib_Author.Where(m => m.status == true).ToList();
            lb._bookentrylist = db.sp_getBookentry().ToList();
            lb._departmentlist = db.tblDepartment.Where(m => m.Status == true).ToList();
            lb._vendorlist = db.tbl_lib_Vendor.Where(m => m.status == true).ToList();
            lb.courselist = db.tbl_CourseMaster.Where(m => m.Status == true).ToList();
           if (lb.Option == 2)
            {
                int? deptid;
                int? courseid;
                int? vendor;
                if (lb.DeptId == 0) { deptid = null; } else { deptid = lb.DeptId; }
                if (lb.LibType == 0) { courseid = null; } else { courseid = lb.LibType; }
                if (lb.JVendorId == 0) { vendor = null; } else { vendor = lb.JVendorId; }
                string jtitle = (lb.JournalTitle == string.Empty) ? null : lb.JournalTitle;
                string jpublisher= (lb.JPublisher == string.Empty) ? null : lb.JPublisher;
                string accessonno = (lb.Number == string.Empty) ? null : lb.Number;
                string jshelfno = (lb.JShelfNo == string.Empty) ? null : lb.JShelfNo;
                lb._journalList = db.sp_GetSearchJournal(lb.Option, deptid, jtitle, courseid, jpublisher, accessonno, vendor, jshelfno).ToList();
                lb.Option = 2;
            }

            else { lb._journalList = db.sp_GetSearchJournal(2, null, null, null, null, null, null, null).ToList(); }
            if (lb.Option == 1)
            {
                int? bdeptid;
                int? bcourseid;
              
                if (lb.Department == 0) { bdeptid = null; } else { bdeptid = lb.Department; }
                if (lb.CourseId == 0) { bcourseid = null; } else { bcourseid = lb.CourseId; }
                string btitle = (lb.booktitle == string.Empty) ? null : lb.booktitle;
                string bpublisher = (lb.PublishedByName == string.Empty) ? null : lb.PublishedByName;
                string baccessonno = (lb.AccessorNo == string.Empty) ? null : lb.AccessorNo;
                string bcallno = (lb.CallNo == string.Empty) ? null : lb.CallNo;
                string authorname = (lb.Authorname == string.Empty) ? null : lb.Authorname;
                string vendorname = (lb.Vendorname == string.Empty) ? null : lb.Vendorname;
                lb._bookandJournallist = db.sp_GetSearchBookAndJournal(lb.Option, btitle, authorname, bcallno, baccessonno, bpublisher, vendorname, bdeptid, bcourseid).ToList();
                lb.Option = 1;
            }
            else { lb._bookandJournallist = db.sp_GetSearchBookAndJournal(1, null, null, null, null, null, null,null,null).Take(10).ToList(); }
            return View(lb);
          
        }
       
   

        public ActionResult BookEntry()
         {
            libBookentry lb = new libBookentry();
           
            lb._departmentlist = db.tblDepartment.Where(m => m.Status == true).ToList();
            lb._authorlist = db.tbl_lib_Author.Where(m => m.status == true).ToList();
            lb._jtypelist = db.tbl_lib_JournalType.Where(m => m.status == true).ToList();
            lb._publisherlist = db.tbl_lib_Publisher.Where(m => m.status == true).ToList();
            lb._vendorlist = db.tbl_lib_Vendor.Where(m => m.status == true).ToList();
            lb.courselist = db.tbl_CourseMaster.Where(m => m.Status == true).ToList();
            lb._bookcategorylist = db.tbl_lib_BookCategory.Where(m => m.status == true).ToList();
            int count = (from p in db.lib_Bookentry
                         select p).Count();
            count = count + 1;
            if (count != 1)
            {
                var lastaccessorno = (from t in db.lib_Bookentry
                                      orderby t.AccessorNo descending
                                      select t.AccessorNo).First();
                int accessorno = 0;
                accessorno = Convert.ToInt32(lastaccessorno) + 1;
                lb.AccessorNo = accessorno.ToString();
            }
            else { lb.AccessorNo = count.ToString(); }
            lb.SerielNumber = count.ToString();
            int count1 = (from q in db.lib_Journal
                         select q).Count();
            count1 = count1 + 1;
           
            lb.Number = count1.ToString();
            return View(lb);

        }
      
        [HttpPost]
        public ActionResult BookEntry(libBookentry _lb,string command)
        {
            
            if (command.Equals("BookSubmit"))
            {
                
                try {
                    int subid = Convert.ToInt32(Session["Userid"].ToString());
                    db.sp_AddBookEntry(_lb.bookid,_lb.booktitle,_lb.CallNo, _lb.Volume, _lb.SerielNumber, _lb.Authorid,
                    _lb.Authorname, _lb.PublishedByid, _lb.PublishedByName, _lb.Edition, _lb.Vendorid, _lb.Vendorname,

                     _lb.Dateofpurchase, _lb.BillNo, _lb.Cost,_lb.AccessorNo,_lb.ShelfNo, true, subid,_lb.CourseId,_lb.DeptId,_lb.BookCategoryid).ToString();



              TempData["Error"] = "Success";
                }
                catch { TempData["Error"] = "Failed"; }
                 }
            if (command.Equals("JournalSubmit"))
            {
               
                try
                {
                    db.sp_AddLibraryJournal(_lb.lib_Jid,_lb.LibType,_lb.Department,_lb.JournalTitle,_lb.LibJVolume,
                        _lb.Number,_lb.IssueDate, _lb.JVendorId, _lb.PurchaseDate,_lb.JBillNo,_lb.IssueType,_lb.JPublisher,_lb.JShelfNo,_lb.JCost).ToString();
                    TempData["Error"] = "Success";

                }
                catch { TempData["Error"] = "Failed"; }





            }
          
           
            _lb._departmentlist = db.tblDepartment.Where(m => m.Status == true).ToList();
         
            return RedirectToAction("BookEntry");
           
        }

        public ActionResult BookEdit(int? bookid)
        {
            libBookentry lb = new libBookentry();
            TempData["Error"] = "";
            lb._departmentlist = db.tblDepartment.Where(m => m.Status == true).ToList();
            lb._authorlist = db.tbl_lib_Author.Where(m => m.status == true).ToList();
            lb._jtypelist = db.tbl_lib_JournalType.Where(m => m.status == true).ToList();
            lb._publisherlist = db.tbl_lib_Publisher.Where(m => m.status == true).ToList();
            lb._vendorlist = db.tbl_lib_Vendor.Where(m => m.status == true).ToList();
            lb.courselist = db.tbl_CourseMaster.Where(m => m.Status == true).ToList();
            lb._bookcategorylist = db.tbl_lib_BookCategory.Where(m => m.status == true).ToList();
            return View("BookEntry", lb);
        }

        public ActionResult JournalEdit(int? lib_Jid)
        {
            libBookentry lb = new libBookentry();
            TempData["Error"] = "";
            lb._departmentlist = db.tblDepartment.Where(m => m.Status == true).ToList();
            lb._authorlist = db.tbl_lib_Author.Where(m => m.status == true).ToList();
            lb._jtypelist = db.tbl_lib_JournalType.Where(m => m.status == true).ToList();
            lb._publisherlist = db.tbl_lib_Publisher.Where(m => m.status == true).ToList();
            lb._vendorlist = db.tbl_lib_Vendor.Where(m => m.status == true).ToList();
            lb.courselist = db.tbl_CourseMaster.Where(m => m.Status == true).ToList();
            lb._bookcategorylist = db.tbl_lib_BookCategory.Where(m => m.status == true).ToList();
            return View("BookEntry", lb);
        }
        public JsonResult FillBookDetails(int bookid)
        {
            var data = db.Sp_GetLibBookDetailsbyId(bookid).FirstOrDefault();
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public JsonResult FillJournalDetails(int jid)
        {
          
            var data = db.lib_Journal.Where(m => m.lib_Jid == jid).FirstOrDefault();
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult BookIssue()
        {
            BookAllocation b = new BookAllocation();

            b._BookIssueList = db.tbl_lib_BookIssue.ToList();
            b._bookandJournallist = db.sp_GetSearchBookAndJournal(1, null, null, null, null, null, null,null,null).ToList();
            return View(b);
        }
        [HttpPost]
        public JsonResult AutoComplete(string prefix)
        {
            var StudentName = (from bi in db.tbl_student
                           where bi.Studnm.StartsWith(prefix)
                           select new {label=bi.Studnm ,
                           val=bi.StudentID}).ToList();
            return Json(StudentName, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult BookAutoComplete(string prefix)
        {
            var BookName = (from bi in db.tbl_BookDetails
                               where bi.BookName.StartsWith(prefix)
                               select new
                               {
                                   label = bi.BookName,
                                   val = bi.CallNo
                               }).ToList();
            return Json(BookName, JsonRequestBehavior.AllowGet);
        }
       

        public JsonResult GetBookIssueDetails(string StudentName, string Studentid,string Stdid)
        {

SchoolManagementSystems/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Entity;
using Common;

namespace SchoolManagementSystems.Controllers
{
    [HandleError]
    public class LoginController : Controller
    {
        SchoolMgmtSysEntities db = new SchoolMgmtSysEntities();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Login(string Username, string Password)
        {
            ViewData["Error"] = "";
            Userviewmodel uvm = new Userviewmodel();
            Dashboardviewmodel dvm = new Dashboardviewmodel();
            Dashboardviewmodel.MyProfileView mpv = new Dashboardviewmodel.MyProfileView();
            string currentdate = CommonUtility.FormatedDateString(DateTime.Now);
            string datemonth = currentdate.Substring(0, 5);
            if (Session["Userid"] != null && Session["Userid"].ToString() != "")
            {
                dvm.Newsdatacollection = db.tbl_news.Where(m => m.Status == true).ToList();
                dvm.BirthdaylistDetails = db.sp_GetBirthdayListDetails().Where(m => m.DOB.ToUpper().Contains(datemonth.ToString())).OrderBy(m => m.Studnm).ToList();

                if (Convert.ToString(Session["Role"]) == "1")
                { return View("../MyProfile/Index", mpv); }
                else { return View("DashBoard", dvm); }
            }
            else
            {
                try
                {
                    uvm.Userdatacollection = db.tbl_user.Where(m => m.UserName == Username && m.Password == Password && m.Status == 1).ToList();
                }
                catch { }
                if (uvm.Userdatacollection != null)
                {
                    if (uvm.Userdatacollection.Count() > 0 && uvm.Userdatacollection[0].Status == 1)
                    {
                        Session["Userid"] = uvm.Userdatacollection[0].Userid.ToString();
                        Session["User"] = uvm.Userdatacollection[0].UserName.ToString();
                        Session["Role"] = uvm.Userdatacollection[0].Type.ToString();
                        Session["Genid"] = uvm.Userdatacollection[0].Genid.ToString();
                        dvm.Newsdatacollection = db.tbl_news.Where(m => m.Status == true).ToList();
                        dvm.BirthdaylistDetails = db.sp_GetBirthdayListDetails().Where(m => m.DOB.ToUpper().Contains(datemonth.ToString())).OrderBy(m => m.Studnm).ToList();
                        if (Convert.ToString(Session["Role"]) == "1")
                        { return View("../MyProfile/Index", mpv); }
                        else { return View("DashBoard", dvm); }
                       
                    }
                    else
                    {
                        ViewData["Error"] = "Either UserName or Password is incorrect / You are not active User!..";
                        return View("Index");
                    }
                }
               
                return View("Index");
            }
        }

        public ActionResult Logout()
        {
            Session.Clear();
            return View("Index");
        }

        public ActionResult ChangePassword()
        {
            Userviewmodel uvm = new Userviewmodel();
            return View(uvm);
        }

        [HttpGet]
        public JsonResult UpdatePassword(int Userid, string OldPassword, string NewPassword)
        {
            Userviewmodel uvm = new Userviewmodel(); string msg = null;
            uvm.checkpassword = db.sp_changepassword(Userid, NewPassword, OldPassword, "check").ToList();
            if (uvm.checkpassword.Count > 0)
            {
                db.sp_changepassword(Userid, NewPassword, OldPassword, "change");
                msg = "Password changed successfully!..";
            }
            else
            {
                msg = "Old password entered is incorrect!..";
            }
            //ViewData["msg"] = msg;
            //return View(ViewData["msg"]);
            return Json(uvm, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult ForgotPassword()
        {
            Userviewmodel uvm = new Userviewmodel();
            return View(uvm);
        }

        public ActionResult GetPassword()
        {
            Userviewmodel uvm = new Userviewmodel();
            return View(uvm);
        }

        public void FillPermission(int modid)
        {
            var per = db.sp_get_permission(Convert.ToInt32(Session["Role"]), modid).ToList();
            for (int i = 0; i < per.Count; i++)
            {
                if (per[i].Permissionid == 1) { ViewData["Add"] = "Allow"; }
                else if (per[i].Permissionid == 2) { ViewData["Modify"] = "Allow"; }
                else if (per[i].Permissionid == 3) { ViewData["View"] = "Allow"; }
                else if (per[i].Permissionid == 4) { ViewData["Delete"] = "Allow"; }
            }
        }

        public ActionResult GetNews(Dashboardviewmodel dash)
        {

            return View("Dashboard");
        }


    }
}

SchoolManagementSystems/Views/Library/BarCode.cshtml
@model Entity.barcodeviewmodel
@{
    ViewBag.Title = "BarCode";
    Layout = "~/Views/shared/_SharedLayout.cshtml";
}
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script type="text/javascript">

    $(document).ready(function () {
        $(document).on('click', "#tblCustomers [id*=chkHeader]", function () {
            if ($(this).is(":checked")) {
                $("#tblCustomers [id*=chkRow]").attr("checked", "checked");
            } else {
                $("#tblCustomers [id*=chkRow]").removeAttr("checked");
            }
        });
        $(document).on('click', "#tblCustomers [id*=chkRow]", function () {
            if ($("#tblCustomers [id*=chkRow]").length == $("#tblCustomers [id*=chkRow]:checked").length) {
                $("#tblCustomers [id*=chkHeader]").attr("checked", "checked");
            } else {
                $("#tblCustomers [id*=chkHeader]").removeAttr("checked");
            }
        });
        $("#CourseId").change(function () {
            $("#DeptId").empty();

            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetCourse")',
                dataType: 'json',
                data: { id: $("#CourseId").val() },
                success: function (course) {
                    if (course != "") {
                        var item = '<option value="0">Select Department</option>';
                        $.each(course, function (i, dclass) {
                            item += '<option value="' + dclass.Value + '">' + dclass.Text + '</option>';
                        });
                        $("#DeptId").append(item);
                    }
                    else {
                        var item = '<option value="0">Select Department</option>';
                        $("#DeptId").append(item);
                    }
                },
                error: function (ex) {
                    alert('Failed to retrieve Department.' + ex);
                }
            });
            return false;
        })

        $("#viewBtn").on("click", function () {

            var courseid = $("#CourseId").val();
            var deptid = $("#DeptId").val();
            var bookcategoryId = $("#BookCategoryid").val();
            $.ajax({
                type: 'GET',
                url: '@Url.Action("GetGenerateBarCode")',

                data: { CourseId:courseid,DeptId: deptid,BookCategoryId:bookcategoryId},
                success: function (data) {

                    $("#result").html(data);
                }, error: function (xhr) {
                    $("#result").html("");
                }
            });

        });

        $("#viewPrint").on("click", function () {

            var courseid = $("#CourseId").val();
            var deptid = $("#DeptId").val();
            var bookcategoryId = $("#BookCategoryid").val();
            $.ajax({
                type: 'GET',
                url: '@Url.Action("GetGeneratePrintBarCode")',

                data: { CourseId: courseid, DeptId: deptid, BookCategoryId: bookcategoryId },
                success: function (data) {

                    $("#result").html(data);
                }, error: function (xhr) {
                    $("#result").html("");
                }
            });

        });



        $("#Generate").click(function () {
            debugger;
        var Generatebarcode = [];
        $('input:checkbox.addcls').each(function (evt) {
            var bookids = ($(this).val());
            if ($(this).prop('checked')) {
                Generatebarcode.push(bookids);

            }
            else {

            }

        });
        if (Generatebarcode != "") {
            var options = {};
            options.type = "POST",
            options.url = '@Url.Action("GenerateBarCode")',
            options.data = JSON.stringify(Generatebarcode);
            options.contentType = "application/json";
            options.success = function (Generatebarcode) {
                $("#msgs").show();
                $("#lblmsgs").text("Book BarCode Generated  successfully!..");
                $("#lblmsgs").css({ "color": "green" });
                $("#lblmsgs").css({ "font-size": "15px" });

            };
            options.error = function (GenerateBarCode) {
                $("#msg1").show();
                $("#lblmsg").text("Error while sending massage !..");
                $("#lblmsg").css({ "color": "orange" });
                $("#lblmsg").css({ "font-size": "15px" });
                $("#tblBooks").html(result);
            };
            $.ajax(options);
        }

    else {
    $("#msg1").show();
    $("#lblmsg").text("Please Fill Select Proper Values ");
    $("#lblmsg").css({ "color": "orange" });
    $("#lblmsg").css({ "font-size": "15px" });


    }
            ReloadPaging();


    });
    });
</script>
<script type="text/javascript">
    function printContent(el) {
           var panel = document.getElementById(el);
           var printWindow = window.open('', '', 'height=400,width=800');
           printWindow.document.write("<html> <head>");
           printWindow.document.write('</head><body><table>');
           printWindow.document.write(panel.innerHTML);
           printWindow.document.write('</table></body></html>');
           printWindow.document.close();
           setTimeout(function () {
               printWindow.print();
           }, 500);
           return true;
       }
</script>
<div class="container-fluid-full">

    <div class="row-fluid">
        @Html.Partial("_LibrarymanagementList")
        <div id="content" class="span10">
            <div class="row-fluid">

                <ul class="breadcrumb">
                    <li>
                        <i class="icon-home"></i>@Html.ActionLink("Home", "Login", "Login")<i class="icon-angle-right"></i>
                        @Html.ActionLink("Library Management", "Index", "Library", "")<i class="icon-angle-right"></i>
                    </li>
                    <li class="active">Bar Code Generator</li>
                </ul>
                <div class="panel-body">
                    <div id="msg" hidden="hidden" class="alert alert-warning" visible="false">
                        <strong><label id="lblmsg"></label></strong>
                    </div>
                    <div id="msgs" hidden="hidden" class="alert alert-success" visible="false">
                        <strong><label id="lblmsgs"></label></strong>
                    </div>
                </div>
                <div class="row-fluid sortable">
                    <div class="box span12">
                        <div class="box-header" data-original-title>
                            <h2><i class="fa fa-edit"></i><span class="break"></span>Bar Code Generator</h2>
                            <div class="box-icon">

                                <a href="#" class="btn-minimize"><i class="fa fa-chevron-up" aria-hidden="true"></i></a>

                            </div>
                        </div>
                      

                        <div class="box-content">
                            <form id="frm" class="form-horizontal">
                                <fieldset>
                                    <legend>Book Barcode List</legend><br />
                                    <div class="control-group span5">
                                        @Html.LabelFor(model => model.CourseId, new { @class = "control-label", @for = "focusedInput" })
                                        <div class="controls">
                                            @Html.DropDownListFor(model => model.CourseId, new SelectList(Model.courselist, "Courseid", "CourseName", "Select Course"), "Select Course", new { @for = "select" })

                                           
                                        </div>
                                    </div>

                                    <div class="control-group span5">
                                        @Html.LabelFor(model => model.DeptId, new { @class = "control-label", @for = "select" })
                                        <div class="controls">
                                            @Html.DropDownListFor(model => model.DeptId, new SelectList(Model._departmentlist, "Dept_id", "Dept_name", "Select Department"), "Select Department", new { @for = "select" })
                                          
                                        </div>
                                    </div>

                                    <div class="control-group span5">
                                        @Html.LabelFor(model => model.BookCategoryid, new { @class = "control-label", @for = "select" })
                                        <div class="controls">
                                            @Html.DropDownListFor(model => model.BookCategoryid, new SelectList(Model._bookcategorylist, "BookCategoryId", "CategoryName", "Select Category"), "Select Category", new { @for = "select" })
                                          
                                        </div>
                                    </div>

                                    <div class="control-group span5 pull-right">
                                        <button id="viewBtn" type="button" class="btn-primary"> View All</button>
                                        &nbsp;&nbsp;
                                        <input type="submit" class="btn-primary" value="Gerate Bar Code" id="Generate" />
                                        &nbsp;&nbsp;
                                        <button id="viewPrint" type="button" class="btn-primary">View BarCode</button>
                                        &nbsp;&nbsp;
                                        <button id="vPrint" type="button" class="btn-primary" onclick="printContent('result')">Print</button>

                                    </div>
                                </fieldset>
                                <div id="result" class="table-responsive">
                                    </div>
</form>
</div>
</div>
</div>
</div></div>
</div>
</div>

SchoolManagementSystems/Views/Library/BookCallStock.cshtml
@model Entity.BookAllocation
@{
    ViewBag.Title = "BookCallStock";
    Layout = "~/Views/shared/_SharedLayout.cshtml";
}
<div class="container-fluid-full">

    <div class="row-fluid">
        @Html.Partial("_LibrarymanagementList")
        <div id="content" class="span10">
            <div class="row-fluid">
                <ul class="breadcrumb">
                    <li>
                        <i class="icon-home"></i>@Html.ActionLink("Home", "Login", "Login")<i class="icon-angle-right"></i>
                        @Html.ActionLink("Library Management", "Index", "Library", "")<i class="icon-angle-right"></i>
                    </li>
                    <li class="active">Book Stock</li>
                </ul>
                <div class="row-fluid sortable">
                    <div class="box span12">
                        <div class="box-header" data-original-title>
                            <h2><i class="fa fa-edit"></i><span class="break"></span>Book Stock</h2>
                            <div class="box-icon">

                                <a href="#" class="btn-minimize"><i class="fa fa-chevron-up" aria-hidden="true"></i></a>

                            </div>
                        </div>
                        <div class="box-content">
                            <div id="result" class="table-responsive">
                                <table class="table table-striped table-bordered bootstrap-datatable datatable">
                                    <thead>
                                        <tr>
                                         
                                            <th>
                                                CallNo
                                            </th>
                                          
                                            <th>
                                               BookName
                                            </th>
                                            <th>
                                                BookQty
                                            </th>
                                            <th>
                                                AllocateQty
                                            </th>
                                            <th>
                                                AvailableQty
                                            </th>
                                           
                                            <th>
                                                LostQty
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model._BookStockList)
            {
                                            <tr>
                                             
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.CallNo)
                                                </td>
                                               
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.BookName)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.BookQty)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.AllocateQty)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.AvailQty)
                                                </td>
                                             
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.LostQty)
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

SchoolManagementSystems/Views/Library/_BookList.cshtml
@model Entity.BookAllocation
<div id="result" class="table-responsive">
    <table class="table tb-parshav tablesorter">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.bookid)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.booktitle)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.Authorname)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.PublishedByName)
                </th>

                <th class="edt">
                    @Html.DisplayName("Action")
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model._bookslist)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TitleName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Authorname)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Publisher)
                    </td>


                    <td>
                        <input type="button" id="@item.Id" class="btn btn-default btn_edit" value="Edit" />

                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>