SchoolManagementSystems/Controllers/AttendanceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Entity;
using System.Net.Mail;
using System.Configuration;
using System.Globalization;
using System.Net;
using System.Collections.Specialized;

namespace SchoolManagementSystems.Controllers
{
    [HandleError]
    [SchoolManagementSystems.MvcApplication.SessionExpire]
    public class AttendanceController : Controller
    {
        //
        // GET: /Attendance/
        SchoolMgmtSysEntities db = new SchoolMgmtSysEntities();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Staff()
        {
            Attendanceviewmodel _avm = new Attendanceviewmodel();
            _avm.Employeelist = db.tbl_employee.ToList();
            return View(_avm);
            //ViewBag.errormessage = "";
            //Attendanceviewmodel _avm = new Attendanceviewmodel();
            //FillPermission(8);
            ////_avm.Classlist = db.tbl_class.Where(c => c.status == true).ToList();
            //if (Search_Data == null || Search_Data == "")
            //    _avm.Employeelist = db.tbl_employee.OrderBy(m => m.Empid).ToList();
            //else
            //    _avm.Employeelist = db.tbl_employee.Where(x => x.FirstName.ToUpper().Contains(Search_Data.ToUpper()) ||
            //                                            x.MiddleName.ToUpper().Contains(Search_Data.ToUpper()) ||
            //                                            x.LastName.ToUpper().Contains(Search_Data.ToUpper())).OrderBy(m => m.Empid).ToList();

            //_avm.Leavelist = db.tbl_leave.Where(x => x.status == true).ToList();

            //return View(_avm);
        }
        public JsonResult GetStudentsSearchData(string id, string Search_Data)
        {
            int Classid = 0;
            if (id != null && id != "")
            {
                Classid = Convert.ToInt32(id);
            }
            Studentviewmodel svm = new Studentviewmodel();
            //var students = db.tbl_student.Where(m => m.Classid == Classid).ToList();
            if (Search_Data == null || Search_Data == "")
                svm.StudentDataCollection = db.sp_GetStudentDataCollection().OrderBy(m => m.Studid).ToList();
            else
                svm.StudentDataCollection = db.sp_GetStudentDataCollection().OrderBy(m => m.Studid).Where(x => x.Studnm.ToUpper().Contains(Search_Data.ToUpper())
                                                                                        || x.StdMobNo.ToUpper().Contains(Search_Data.ToUpper())
                                                                                        || x.StudEmail.ToUpper().Contains(Search_Data.ToUpper())
                                                                                        || x.YearName.ToUpper().Contains(Search_Data.ToUpper())).ToList();
            var students = svm.StudentDataCollection.Where(x => x.Classid == Classid).ToList();
            return Json(students, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetStudents(string id, string id2, string id3)
        {
            int Classid = 0;
            int DepartmentId = 0;
            int yearid = 0;
            if (id != null && id != "" && id2 != null && id2 != "" && id3 != null && id3 != "")
            {
                DepartmentId = Convert.ToInt32(id3);
                yearid = Convert.ToInt32(id2);
                Classid = Convert.ToInt32(id);
            }
            var students = db.tbl_student.Where(m => (m.Classid == Classid && m.Dept_Id == DepartmentId && m.courseyearid == yearid)).Select(m => new { m.Studid, m.Studnm, m.Studfathernm, m.Studmothernm, m.StudEmail, m.Classid, m.FatherEmail, m.MotherEmail, m.Countryid, m.Stateid, m.Cityid, m.RollNo }).ToList();
            return Json(students, JsonRequestBehavior.AllowGet);
        }
        public ActionResult StaffAttendance(Attendanceviewmodel avm, string evt, int id)
        {
            if (evt == "submit")
            {
                var employee = db.tbl_employee.Select(x => x.Empid).ToList();
                var CHECK = db.tbl_StaffAttendance.Where(x => x.AttendanceDate == (avm.StaffAttendanceDate) && employee.Contains(x.StaffId.Value) && x.Absent == null ? true : false != false).ToList();
                if (CHECK.Count > 0)
                {
                    TempData["ErrorMessage"] = "Attendance Already exists!!";
                }
                else
                {
                    db.sp_EmployeeAttendance(avm.StaffAttendanceDate);
                    TempData["ErrorMessage"] = "Attendance Added Successfully!!";
                }
            }
            return RedirectToAction("staff");
        }
        public ActionResult Student()
        {
            ViewBag.errormessage = "";
            Attendanceviewmodel _avm = new Attendanceviewmodel();
            FillPermission(9);
            _avm.YearList = new List<tbl_YearMaster>();
            _avm.DepartmentList = new List<tblDepartment>();
            _avm.SubjectList = new List<tbl_subject>();
            _avm.DivisionList = new List<tbl_division>();
            int Empid;
            int roleid;
            try { Empid = Convert.ToInt32(Session["Genid"].ToString()); } catch { Empid = 0; }
            try { roleid = Convert.ToInt32(Session["Role"].ToString()); } catch { roleid = 0; }
            _avm._courselist = db.sp_getTeacherCourse(Empid, roleid).ToList();
            _avm.SessionList = db.tbl_SessionMaster.OrderBy(m => m.SessionName).ToList();
            _avm._Lecturelist = db.tbl_LectTimeSetUp.OrderBy(m => m.LecNo).ToList();
            return View(_avm);
        }
        public JsonResult GetYearClass(string depid, string cid)
        {
            int coureid = 0;
            int detid = 0;
            if (depid != null && depid != "" && cid != null && cid != "")
            {
                coureid = Convert.ToInt32(cid);
                detid = Convert.ToInt32(depid);
            }
            int Empid;
            int roleid;
            try { Empid = Convert.ToInt32(Session["Genid"].ToString()); } catch { Empid = 0; }
            try { roleid = Convert.ToInt32(Session["Role"].ToString()); } catch { roleid = 0; }
            List<sp_getTeacherCourseYear_Result> yeardata = db.sp_getTeacherCourseYear(Empid, roleid, coureid, detid).ToList();

            return Json(new SelectList(yeardata, "yearid", "YearName"));

        }
        public JsonResult GetDepartment(string id)
        {
            int courseid = 0;
            if (id != null && id != "")
            {
                courseid = Convert.ToInt32(id);
            }

            var DClass = from post in db.tbl_Course
                         join meta in db.tblDepartment on post.Dept_id equals meta.Dept_id
                         where post.Course_id == courseid && post.status == true
                         select new { meta.Dept_id, meta.Dept_name };

            return Json(new SelectList(DClass, "Dept_id", "Dept_name"));
        }


        public JsonResult GetCourseTeacherDepartment(string id)
        {
            int courseid = 0;
            if (id != null && id != "")
            {
                courseid = Convert.ToInt32(id);
            }
            int Empid;
            int roleid;
            try { Empid = Convert.ToInt32(Session["Genid"].ToString()); } catch { Empid = 0; }
            try { roleid = Convert.ToInt32(Session["Role"].ToString()); } catch { roleid = 0; }

            List<sp_getTeacherCourseDepartment_Result> DClass = db.sp_getTeacherCourseDepartment(Empid, roleid, courseid).ToList();

            return Json(new SelectList(DClass, "Dept_id", "Dept_name"));
        }
        public JsonResult GetDivision(string id)
        {
            int classid = 0;
            if (id != null && id != "")
            {
                classid = Convert.ToInt32(id);
            }
            var division = db.tbl_division.Where(m => m.Classid == classid).ToList();
            return Json(new SelectList(division, "Divisionid", "DivisionName"));
        }
        public JsonResult GetSubject(string id, string dept, string year)
        {
            int yearid = 0;
            int Courseid = 0;
            int deptid = 0;
            if (id != null && id != "" && dept != null && dept != "" && year != null && year != "")
            {
                Courseid = Convert.ToInt32(id);
                yearid = Convert.ToInt32(year);
                deptid = Convert.ToInt32(dept);
            }
           int Empid = Convert.ToInt32(Session["Genid"].ToString());
           int roleid = Convert.ToInt32(Session["Role"].ToString());
           
            var subject = db.sp_GetTeacherSubject(Empid, roleid, Courseid, deptid, yearid).ToList();
            return Json(new SelectList(subject, "Subjectid", "SubjectNm"));
        }
        //public ActionResult GetYear(int dept_id, int courseid,int academicyear)
        //{ 
        //    //Attendanceviewmodel _avm = new Attendanceviewmodel();
        //    //_avm.tblcourse = new List<tbl_CourseYearMaster>();
        //    // _avm.YearList = new List<tbl_YearMaster>();
        //    // tbl_CourseYearMaster yClass = db.tbl_CourseYearMaster.Where(m => m.dept_id == deptid && m.courseid == courseid).FirstOrDefault();
        //    //var data1 = db.tbl_YearMaster.Where(m => m.yearid == academicyear).ToList();
        //    //return Json(new SelectList(data1, "yearid", "YearName"));
        //    //var query = from c in db.tbl_CourseYearMaster
        //    //            join o in db.tbl_YearMaster on c.academicyear equals o.yearid
        //    //            where c.dept_id == dept_id && c.courseid == courseid
        //    //            select new { o.yearid, o.YearName };
        //    //_avm.ylist = new SelectList(query, "yearid", "YearName");

        //    //_avm.year = "NY";
        //    //return View(_avm);

SchoolManagementSystems/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Entity;
using Common;

namespace SchoolManagementSystems.Controllers
{
    [HandleError]
    public class LoginController : Controller
    {
        SchoolMgmtSysEntities db = new SchoolMgmtSysEntities();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Login(string Username, string Password)
        {
            ViewData["Error"] = "";
            Userviewmodel uvm = new Userviewmodel();
            Dashboardviewmodel dvm = new Dashboardviewmodel();
            Dashboardviewmodel.MyProfileView mpv = new Dashboardviewmodel.MyProfileView();
            string currentdate = CommonUtility.FormatedDateString(DateTime.Now);
            string datemonth = currentdate.Substring(0, 5);
            if (Session["Userid"] != null && Session["Userid"].ToString() != "")
            {
                dvm.Newsdatacollection = db.tbl_news.Where(m => m.Status == true).ToList();
                dvm.BirthdaylistDetails = db.sp_GetBirthdayListDetails().Where(m => m.DOB.ToUpper().Contains(datemonth.ToString())).OrderBy(m => m.Studnm).ToList();

                if (Convert.ToString(Session["Role"]) == "1")
                { return View("../MyProfile/Index", mpv); }
                else { return View("DashBoard", dvm); }
            }
            else
            {
                try
                {
                    uvm.Userdatacollection = db.tbl_user.Where(m => m.UserName == Username && m.Password == Password && m.Status == 1).ToList();
                }
                catch { }
                if (uvm.Userdatacollection != null)
                {
                    if (uvm.Userdatacollection.Count() > 0 && uvm.Userdatacollection[0].Status == 1)
                    {
                        Session["Userid"] = uvm.Userdatacollection[0].Userid.ToString();
                        Session["User"] = uvm.Userdatacollection[0].UserName.ToString();
                        Session["Role"] = uvm.Userdatacollection[0].Type.ToString();
                        Session["Genid"] = uvm.Userdatacollection[0].Genid.ToString();
                        dvm.Newsdatacollection = db.tbl_news.Where(m => m.Status == true).ToList();
                        dvm.BirthdaylistDetails = db.sp_GetBirthdayListDetails().Where(m => m.DOB.ToUpper().Contains(datemonth.ToString())).OrderBy(m => m.Studnm).ToList();
                        if (Convert.ToString(Session["Role"]) == "1")
                        { return View("../MyProfile/Index", mpv); }
                        else { return View("DashBoard", dvm); }
                       
                    }
                    else
                    {
                        ViewData["Error"] = "Either UserName or Password is incorrect / You are not active User!..";
                        return View("Index");
                    }
                }
               
                return View("Index");
            }
        }

        public ActionResult Logout()
        {
            Session.Clear();
            return View("Index");
        }

        public ActionResult ChangePassword()
        {
            Userviewmodel uvm = new Userviewmodel();
            return View(uvm);
        }

        [HttpGet]
        public JsonResult UpdatePassword(int Userid, string OldPassword, string NewPassword)
        {
            Userviewmodel uvm = new Userviewmodel(); string msg = null;
            uvm.checkpassword = db.sp_changepassword(Userid, NewPassword, OldPassword, "check").ToList();
            if (uvm.checkpassword.Count > 0)
            {
                db.sp_changepassword(Userid, NewPassword, OldPassword, "change");
                msg = "Password changed successfully!..";
            }
            else
            {
                msg = "Old password entered is incorrect!..";
            }
            //ViewData["msg"] = msg;
            //return View(ViewData["msg"]);
            return Json(uvm, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult ForgotPassword()
        {
            Userviewmodel uvm = new Userviewmodel();
            return View(uvm);
        }

        public ActionResult GetPassword()
        {
            Userviewmodel uvm = new Userviewmodel();
            return View(uvm);
        }

        public void FillPermission(int modid)
        {
            var per = db.sp_get_permission(Convert.ToInt32(Session["Role"]), modid).ToList();
            for (int i = 0; i < per.Count; i++)
            {
                if (per[i].Permissionid == 1) { ViewData["Add"] = "Allow"; }
                else if (per[i].Permissionid == 2) { ViewData["Modify"] = "Allow"; }
                else if (per[i].Permissionid == 3) { ViewData["View"] = "Allow"; }
                else if (per[i].Permissionid == 4) { ViewData["Delete"] = "Allow"; }
            }
        }

        public ActionResult GetNews(Dashboardviewmodel dash)
        {

            return View("Dashboard");
        }


    }
}

SchoolManagementSystems/Views/Attendance/ApproveLeave.cshtml
@model Entity.Attendanceviewmodel
@{
    ViewBag.Title = "ApproveLeave";
    Layout = "~/Views/shared/_SharedLayout.cshtml";
}
<script type="text/javascript">
    $(document).ready(function () {
        FillPermission();
        $(".Approve").click(function () {
            var Tid = this.id;
            if ($(this).prop("checked") == true) {
                var d = 1;
            }

            else if ($(this).prop("checked") == false) {
                var d = 0;
            }
            $.ajax({
                type: 'POST',
                url: '@Url.Action("Approve")',
                dataType: 'JSON',
                data: { id: Tid, check: d },
                success: function (data) {

                    if (data != null) {
                    }
                    else {
                    }
                }
            });
        });
        $(".delete").click(function () {
            var Tid = this.id;
            var act = 'Delete';
            var flag = confirm('Are you sure you want to delete this Leave?');
            if (flag) {
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("DeleteLeave")',
                    dataType: 'json',
                    data: { id: Tid },
                    success: function (result) {
                        $("#result").html(result);
                    }
                });
            }
        });
        ReloadPaging();
    });
</script>
@Html.Partial("_PermissionHiddenFlds")
<div class="container-fluid-full">
             
		<div class="row-fluid">
          @Html.Partial("_EmployeeSubMenuList")
	<div id="content" class="span10">
        	<div class="row-fluid">
                   
              
           
                    <ul class="breadcrumb">
                  <li><i class="icon-home"></i>@Html.ActionLink("Home", "Login", "Login")<i class="icon-angle-right"></i>
                        @Html.ActionLink("Attendance Management", "Index", "Attendance", "")<i class="icon-angle-right"></i></li>
                        <li class="active">Approve Leave</li>
                    </ul>
                   <div class="row-fluid sortable">
              <div class="box span12">
					<div class="box-header" data-original-title>
						<h2><i class="fa fa-edit"></i><span class="break"></span>Form Elements</h2>
						<div class="box-icon">
						
							<a href="#" class="btn-minimize"><i class="fa fa-chevron-up" aria-hidden="true"></i></a>
						
						</div>
					</div>
                               		<div class="box-content span11">
                      <div class="box-content span12">
					
                            <!-- table start -->
                            <div class="table-responsive">
                                <table id="result" class="table table-striped table-bordered bootstrap-datatable datatable">
                                    <thead>
                                        <tr>
                                            <th>
                                                @Html.DisplayName("ID")
                                            </th>
                                            <th>
                                                @Html.DisplayName("Employee")
                                            </th>
                                            <th>
                                                @Html.DisplayName("Leave Start Date")
                                            </th>
                                            <th>
                                                @Html.DisplayName("Leave End Date")
                                            </th>
                                            <th>
                                                @Html.DisplayName("Leave Type")
                                            </th>
                                            <th>
                                                @Html.DisplayName("Description")
                                            </th>
                                            <th>
                                                @Html.DisplayName("Is Approve")
                                            </th>
                                            <th>
                    Action
                </th>                   
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model.EmployeeLeavelist)
                                        {
                                            <tr>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Leaveid)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Employee)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.LeaveStartDate)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.LeaveEndDate)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.leavename)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Description)
                                                </td>
                                                <td>
                                                    <input type="checkbox" id="@item.Leaveid" class="Approve" />
                                                </td>
                                                <td>
                                                    <input type="button" id="@item.Leaveid" class="btn btn-default delete" value="Reject" />
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        
                </div>
        </div>

        </div>
    </div>
</div>
   
            </div>
    </div>
    </div>

SchoolManagementSystems/Views/Attendance/Division.cshtml
 @model Entity.studentdivisionmodel
@{
    ViewBag.Title = "Division";
    Layout = "~/Views/shared/_SharedLayout.cshtml";
}


<div class="container-fluid-full">
             
		<div class="row-fluid">
           @Html.Partial("_AttendanceMenuList")
	<div id="content" class="span10">
        	<div class="row-fluid">
              
                    <ul class="breadcrumb">
                        <li><i class="icon-home"></i>@Html.ActionLink("Home", "Login", "Login")<i class="icon-angle-right"></i>
                        @Html.ActionLink("Attendance Management", "Index", "Attendance", "")<i class="icon-angle-right"></i></li>
                        <li class="active">Student Attendances</li>
                        <div id="srch_criteria" style="float: right;display:none;">
                            @*@using (Html.BeginForm())
                            {*@
                            @Html.TextBox("Search_Data", ViewBag.FilterValue as string)
                            <input type="submit" id="srch" value="Find" />
                            @*}*@
                        </div>
                    </ul>
                 <div class="panel-body"> 
                  <div id="msg" hidden="hidden" class="alert alert-warning" visible="false">
	                <strong><label id="lblmsg"></label></strong> 
	                </div>
                <div id="msgs" hidden="hidden" class="alert alert-success" visible="false">
	              <strong><label id="lblmsgs"></label></strong> 
                </div>
                </div>
               <div class="row-fluid sortable">
              <div class="box span12">
					<div class="box-header">
						<h2><i class="fa fa-edit"></i><span class="break"></span>Form Elements</h2>
						<div class="box-icon">
						
							<a href="#" class="btn-minimize"><i class="fa fa-chevron-up" aria-hidden="true"></i></a>
						
						</div>
					</div>
                               		<div class="box-content">
						<form id="frm" class="form-horizontal">
                              
						
                                  <fieldset>
                                            @using (Html.BeginForm("ClassStudentAttendance", "Attendance", FormMethod.Post, new { enctype = "multipart/form-data", id = "frm",@class="form-horizontal" }))
                                            {
                                                @Html.ValidationSummary(true)
                                                <div>
                                                    <h2 style="color:red;">
                                                        @TempData["ErrorMessage"]
                                                    </h2>
                                                </div>
                                              <div id="Contentid" class="control-group">
                                        @Html.LabelFor(model => model.id, new {  @class="control-label", @for="focusedInput"  })
                                         <div class="controls">
                                        @Html.EditorFor(model => model.id, new {  @class="input-xlarge focused"  })
                                        @Html.ValidationMessageFor(model => model.id)
                                             </div>
                                    </div>
                                                <div class="control-group span5">
                                                    @Html.LabelFor(model => model.studentid, new { @class = "control-label" })
                                                       <div class="controls">
                                                    @Html.DropDownListFor(model => model.studentid, new SelectList(Model.Classlist, "Classid", "Classnm", "Select Class"), "Select Class")
                                                    @Html.ValidationMessageFor(model => model.studentid)
                                                           </div>
                                                </div>
                                                 <div class="control-group span5">
                                                    @Html.LabelFor(model => model.divisionid, new { @class = "control-label" })
                                                       <div class="controls">
                                                    @Html.DropDownListFor(model => model.divisionid, new SelectList(Model.YearList, "yearid", "YearName", "Select Year"), "Select Year")
                                                    @Html.ValidationMessageFor(model => model.divisionid)
                                                           </div>
                                                </div>
                                                 <div class="control-group span5">
                                                    @Html.LabelFor(model => model.courseid, new { @class = "control-label" })
                                                       <div class="controls">
                                                    @Html.DropDownListFor(model => model.courseid, new SelectList(Model.DivisionList, "Divisionid", "DivisionName", "Select Division"), "Select Division")
                                                    @Html.ValidationMessageFor(model => model.courseid)
                                                           </div>
                                                </div>
                                                <div class="control-group span5">
                                                    @Html.LabelFor(model => model.departmentid, new { @class = "control-label" })
                                                       <div class="controls">
                                                    @Html.DropDownListFor(model => model.departmentid, new SelectList(Model.DivisionList, "Divisionid", "DivisionName", "Select Division"), "Select Division")
                                                    @Html.ValidationMessageFor(model => model.departmentid)
                                                           </div>
                                                </div>
                                                <div class="control-group span5">
                                                    @Html.LabelFor(model => model.yearid, new { @class = "control-label" })
                                                       <div class="controls">
                                                    @Html.DropDownListFor(model => model.yearid, new SelectList(Model.DivisionList, "Divisionid", "DivisionName", "Select Division"), "Select Division")
                                                    @Html.ValidationMessageFor(model => model.yearid)
                                                           </div>
                                                </div>
                                                <div class="control-group span5" id="staffreason" style="display: none;">
                                                </div>
                                             
                                                    <div>
                                            <input type="button" class="btn btn-primary" id="insert" value="submit" />
                                        </div>
                                              
                                                
                                              
                                                  
                                               
                                            }
                                                 </fieldset>
                                </form>
					
					</div>
				</div><!--/span-->
			
			</div><!--/row-->
                                                
                                                 <div class="row-fluid sortable">
              <div class="box span12">
                  	<div class="box-header" data-original-title>
						<h2><i class="fa fa-edit"></i><span class="break"></span>Form Elements</h2>
						<div class="box-icon">
						
							<a href="#" class="btn-minimize"><i class="fa fa-chevron-up" aria-hidden="true"></i></a>
						
						</div>
					</div> 
                  <div class="box-content">
                                               <div id="header" class="table-responsive">
                                        </div>
                                        <div id="result" class="table-responsive">
                                        </div>
                                                </div>
                                             
                                                

                                         </div>
        </div>
             
    </div>
</div>
   
            </div>
    </div>