SchoolManagementSystems/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Entity;
using Common;

namespace SchoolManagementSystems.Controllers
{
    [HandleError]
    public class LoginController : Controller
    {
        SchoolMgmtSysEntities db = new SchoolMgmtSysEntities();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Login(string Username, string Password)
        {
            ViewData["Error"] = "";
            Userviewmodel uvm = new Userviewmodel();
            Dashboardviewmodel dvm = new Dashboardviewmodel();
            Dashboardviewmodel.MyProfileView mpv = new Dashboardviewmodel.MyProfileView();
            string currentdate = CommonUtility.FormatedDateString(DateTime.Now);
            string datemonth = currentdate.Substring(0, 5);
            if (Session["Userid"] != null && Session["Userid"].ToString() != "")
            {
                dvm.Newsdatacollection = db.tbl_news.Where(m => m.Status == true).ToList();
                dvm.BirthdaylistDetails = db.sp_GetBirthdayListDetails().Where(m => m.DOB.ToUpper().Contains(datemonth.ToString())).OrderBy(m => m.Studnm).ToList();

                if (Convert.ToString(Session["Role"]) == "1")
                { return View("../MyProfile/Index", mpv); }
                else { return View("DashBoard", dvm); }
            }
            else
            {
                try
                {
                    uvm.Userdatacollection = db.tbl_user.Where(m => m.UserName == Username && m.Password == Password && m.Status == 1).ToList();
                }
                catch { }
                if (uvm.Userdatacollection != null)
                {
                    if (uvm.Userdatacollection.Count() > 0 && uvm.Userdatacollection[0].Status == 1)
                    {
                        Session["Userid"] = uvm.Userdatacollection[0].Userid.ToString();
                        Session["User"] = uvm.Userdatacollection[0].UserName.ToString();
                        Session["Role"] = uvm.Userdatacollection[0].Type.ToString();
                        Session["Genid"] = uvm.Userdatacollection[0].Genid.ToString();
                        dvm.Newsdatacollection = db.tbl_news.Where(m => m.Status == true).ToList();
                        dvm.BirthdaylistDetails = db.sp_GetBirthdayListDetails().Where(m => m.DOB.ToUpper().Contains(datemonth.ToString())).OrderBy(m => m.Studnm).ToList();
                        if (Convert.ToString(Session["Role"]) == "1")
                        { return View("../MyProfile/Index", mpv); }
                        else { return View("DashBoard", dvm); }
                       
                    }
                    else
                    {
                        ViewData["Error"] = "Either UserName or Password is incorrect / You are not active User!..";
                        return View("Index");
                    }
                }
               
                return View("Index");
            }
        }

        public ActionResult Logout()
        {
            Session.Clear();
            return View("Index");
        }

        public ActionResult ChangePassword()
        {
            Userviewmodel uvm = new Userviewmodel();
            return View(uvm);
        }

        [HttpGet]
        public JsonResult UpdatePassword(int Userid, string OldPassword, string NewPassword)
        {
            Userviewmodel uvm = new Userviewmodel(); string msg = null;
            uvm.checkpassword = db.sp_changepassword(Userid, NewPassword, OldPassword, "check").ToList();
            if (uvm.checkpassword.Count > 0)
            {
                db.sp_changepassword(Userid, NewPassword, OldPassword, "change");
                msg = "Password changed successfully!..";
            }
            else
            {
                msg = "Old password entered is incorrect!..";
            }
            //ViewData["msg"] = msg;
            //return View(ViewData["msg"]);
            return Json(uvm, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult ForgotPassword()
        {
            Userviewmodel uvm = new Userviewmodel();
            return View(uvm);
        }

        public ActionResult GetPassword()
        {
            Userviewmodel uvm = new Userviewmodel();
            return View(uvm);
        }

        public void FillPermission(int modid)
        {
            var per = db.sp_get_permission(Convert.ToInt32(Session["Role"]), modid).ToList();
            for (int i = 0; i < per.Count; i++)
            {
                if (per[i].Permissionid == 1) { ViewData["Add"] = "Allow"; }
                else if (per[i].Permissionid == 2) { ViewData["Modify"] = "Allow"; }
                else if (per[i].Permissionid == 3) { ViewData["View"] = "Allow"; }
                else if (per[i].Permissionid == 4) { ViewData["Delete"] = "Allow"; }
            }
        }

        public ActionResult GetNews(Dashboardviewmodel dash)
        {

            return View("Dashboard");
        }


    }
}

SchoolManagementSystems/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Entity;
using BAL;
using System.IO;
using System.Configuration;
using System.Net.Mail;
using System.Web.Helpers;
using System.Data;
using System.Text;
using Ionic.Zip;
using System.Web.UI.WebControls;
using System.Web.UI;
using System.Net;
using System.Collections.Specialized;
using Common;
using System.Web.Script.Serialization;

namespace SchoolManagementSystems.Controllers
{
    [HandleError]
    public class StudentController : Controller
    {
        SchoolMgmtSysEntities db = new SchoolMgmtSysEntities();
        [HttpGet]
        public ActionResult Index(string Search_Data)
        {
            Studentviewmodel svm = new Studentviewmodel();
            FillPermission(4);
            int Empid;
            int roleid;
            try { Empid = Convert.ToInt32(Session["Genid"].ToString()); } catch { Empid = 0; }
            try { roleid = Convert.ToInt32(Session["Role"].ToString()); } catch { roleid = 0; }
            svm._courselist = db.sp_getTeacherCourse(Empid, roleid).ToList();

            svm.YearList = new List<tbl_YearMaster>();
            svm.DepartmentList = new List<tblDepartment>();
            svm.StudentDataCollection = new List<sp_GetStudentDataCollection_Result>();
            return View(svm);
        }
        [HttpPost]
        public ActionResult Index(Studentviewmodel svm)
        {

            int Empid;
            int roleid;
            try { Empid = Convert.ToInt32(Session["Genid"].ToString()); } catch { Empid = 0; }
            try { roleid = Convert.ToInt32(Session["Role"].ToString()); } catch { roleid = 0; }
            svm._courselist = db.sp_getTeacherCourse(Empid, roleid).ToList();

            svm.YearList = new List<tbl_YearMaster>();
            svm.DepartmentList = new List<tblDepartment>();


            if (svm.Classid.ToString() != null && svm.Classid.ToString() != "" && svm.courseyear.ToString() != null && svm.courseyear.ToString() != "" && svm.DepartmentId.ToString() != null && svm.DepartmentId.ToString() != "")
            {
                svm.StudentDataCollection = db.sp_GetStudentDataCollection().OrderBy(m => m.Studid).Where(x => x.Classid.ToString().ToUpper().Contains(svm.Classid.ToString()) && x.Dept_id.ToString().Contains(svm.DepartmentId.ToString()) && x.courseyearid.ToString().Contains(svm.courseyear.ToString())).ToList();
            }
            else
            {
                svm.StudentDataCollection = new List<sp_GetStudentDataCollection_Result>();
            } 
           

            return View(svm);
        }
        public ActionResult Admission(int? Studid)
        {
            Studentviewmodel svm = new Studentviewmodel();
            FillPermission(3);
            svm.courselist = db.tbl_CourseMaster.Where(m => m.Status == true).ToList();
            svm.select = db.CONFIGMASTERs.Where(m => (m.CONFIGNAME == "SelectOption" && m.CONFIGKEY == "SelectValue")).ToList();
            svm.Translist = db.tbl_transport.Where(m => m.status == true).ToList();
            svm.catlist = db.tbl_category.Where(m => m.status == true).ToList();
            svm.departmentlistdetails = db.tblDepartment.Where(m => m.Dept_id != 0).ToList();
            svm.academicyear = GetYear();
            svm.yearlist = db.tbl_YearMaster.Where(m => m.Status == true).ToList();
            List<SelectListItem> test = new List<SelectListItem>();
            foreach (var r in svm.catlist)
            {
                test.Add(new SelectListItem { Text = r.catname, Value = r.catid.ToString() });
            }
            ViewData["appList"] = test;
            List<SelectListItem> subcat = new List<SelectListItem>();
            ViewData["subcatList"] = subcat;
            List<SelectListItem> prd = new List<SelectListItem>();
            ViewData["prdList"] = prd;
            svm.countrylist = db.tbl_country.Where(m => m.status == true).ToList();
            svm.bloodgrouplist = db.tbl_bloodgroup.Where(m => m.status == true).ToList();
            svm.castelist = new List<tbl_caste>();
            svm.religionlist = db.tbl_religion.Where(m => m.status == true).ToList();
            svm.categorylist = db.tbl_StudentCategory.Where(m => m.status == true).ToList();
            svm.occupationlist = db.tbl_occupation.Where(m => m.status == true).ToList();
            svm.qualificationlist = db.tbl_qualification.Where(m => m.status == true).ToList();
            svm.statelist = new List<tbl_state>();
            svm.citylist = new List<tbl_city>();
            return View("Admission", svm);
        }
        public JsonResult FillStudentDetails(int studid)
        {
            var data = db.tbl_student.Where(m => m.Studid == studid).FirstOrDefault();
            TempData["Docs"] = data.Docs;
            return Json(data,JsonRequestBehavior.AllowGet);
        }
        public JsonResult FillOnlineStudentDetails(int studid)
        {
            var data = db.tbl_online_student.Where(m => m.Studid == studid).FirstOrDefault();
            TempData["Docs"] = data.Docs;
            //JavaScriptSerializer jss = new JavaScriptSerializer();
            //jss.MaxJsonLength = Int32.MaxValue;
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        public JsonResult CheckStudEmail(string Email)
        {
            var data = db.tbl_student.Where(m => m.StudEmail == Email).Select(m => m.StudEmail).FirstOrDefault();
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        public JsonResult Getcducation(string Studid)
        {
            int studentid = 0;
            if (Studid != null && Studid != "")
            {
                studentid = Convert.ToInt32(Studid);
            }
            var collage = db.tbl_collageeducationdetails.Where(m => m.Studid == studentid).FirstOrDefault();
            return Json(collage, JsonRequestBehavior.AllowGet);
        }
        public JsonResult Getseducation(string Studid)
        {
            int studentid = 0;
            if (Studid != null && Studid != "")
            {
                studentid = Convert.ToInt32(Studid);
            }
            var school = db.secondaryeducationdetails.Where(m => m.Studid == studentid).FirstOrDefault();
            return Json(school, JsonRequestBehavior.AllowGet);
        }
        public JsonResult Gethsc(string Studid)
        {
            int studentid = 0;
            if (Studid != null && Studid != "")
            {
                studentid = Convert.ToInt32(Studid);
            }
            var school = db.hsceducationdetails.Where(m => m.Studid == studentid).FirstOrDefault();
            return Json(school, JsonRequestBehavior.AllowGet);
        }
        public JsonResult Getpg(string Studid)
        {
            int studentid = 0;
            if (Studid != null && Studid != "")
            {
                studentid = Convert.ToInt32(Studid);
            }
            var school = db.pgeducationdetails.Where(m => m.Studid == studentid).FirstOrDefault();
            return Json(school, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetProductsexclude(string subcats)
        {
            string[] s = subcats.Split(',');
            List<SelectListItem> prd = new List<SelectListItem>();
            for (int i = 0; i < s.Count(); i++)
            {
                var data = db.sp_getproductsbycatexclude(s[i].ToString()).ToList();
                foreach (var r in data.ToList())
                {
                    prd.Add(new SelectListItem { Text = r.Product, Value = r.Productid.ToString() });
                }
            }
            var prds = prd;
            return Json(prds, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetProducts(string subcats)
        {
            string[] s = subcats.Split(',');
            List<SelectListItem> prd = new List<SelectListItem>();
            for (int i = 0; i < s.Count(); i++)
            {
                if (s[i] != "")
                {
                    var data = db.sp_getproductsbycat(s[i].ToString()).ToList();
                    foreach (var r in data.ToList())
                    {
                        prd.Add(new SelectListItem { Text = r.Product, Value = r.Productid.ToString() });
                    }
                }
            }
            var prds = prd;
            return Json(prds, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetSubcats(string cats)
        {
            string[] s = cats.Split(',');
            StringBuilder exclude = new StringBuilder();
            List<SelectListItem> subcat = new List<SelectListItem>();
            for (int i = 0; i < s.Count(); i++)
            {
                var data = db.sp_getsubcatbycat(s[i].ToString()).ToList();
                if (data.Count() != 0)
                {
                    foreach (var r in data.ToList())
                    {
                        subcat.Add(new SelectListItem { Text = r.SubCategoryname, Value = r.SubCategoryid.ToString() });
                    }
                }
                else
                {
                    exclude.Append(s[i].ToString() + ",");
                }
            }
            var result = new { subcats = subcat, prds = exclude.ToString() };
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetTransportDetails(int busid)
        {
            var data = db.tbl_transport.Where(m => m.busid == busid).FirstOrDefault();
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetStates(string id)
        {
            int countryid = 0;
            if (id != null && id != "")
            {
                countryid = Convert.ToInt32(id);
            }
            var states = db.tbl_state.Where(m => m.Countryid == countryid).ToList();
            return Json(new SelectList(states, "Stateid", "StateName"));

SchoolManagementSystems/Views/Timetable/_Timetablelist.cshtml
@model Entity.timetableviewmodel
<div id="result" class="table-responsive">
    <table class="table table-striped table-bordered bootstrap-datatable datatable">
    <thead>
        <tr>
            <th>
                @Html.DisplayName("ID")
            </th>
            <th>
                @Html.DisplayName("Course")
            </th>
            <th>
                @Html.DisplayName("Department")
            </th>
            <th>
                @Html.DisplayName("Year")
            </th>
            <th>
                @Html.DisplayName("Day Order")
            </th>
            <th>
                @Html.DisplayName("LecNo.")
            </th>
            <th>
                @Html.DisplayName("SubjectCode")
            </th>
            <th>
                @Html.DisplayName("Subject")
            </th>
            @*<th>
                @Html.DisplayName("Start Time")
            </th>
            <th>
                @Html.DisplayName("End Time")
            </th>*@
            <th>
                @Html.DisplayName("Teacher")
            </th>
            <th class="edt">
                Action
            </th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model._Timetablelist)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Tid)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Classid)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Dept_name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.yearid)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Day)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LecNo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SubjectCode)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Subjectid)
                </td>
                @*<td>
                    @Html.DisplayFor(modelItem => item.LecTime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LecETime)
                </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.EmpId)
                </td>
                <td>
                    <input type="button" id="@item.Tid" class="btn btn-default btn_edit edit" value="Edit" />
                    @*<input type="button" id="@item.Tid" class="btn btn-default btn_delete delete" value="Delete" />*@
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>

SchoolManagementSystems/Views/Timetable/_publishedtimetable.cshtml
@model Entity.timetableviewmodel
<div id="result" class="table-responsive">
    <table class="table table-striped table-bordered bootstrap-datatable datatable">
        <thead>
            <tr>
                <th colspan="7">
                    <div class="panel-heading text-center">
                        <img src="../../img/NACCASImage.jpg" height="39" width="45" /><br>
                        <font size="1">
                            <b>NANJIL CATHOLIC COLLEGE OF ARTS AND SCIENCE</b><br /><b>
                               Time Table List<br />
                                <br />
                            </b>
                        </font>
                    </div>
                </th>



            </tr>
            <tr>
                <th colspan="2">
                    @Html.DisplayName("CourseName")
                </th>
                <th colspan="6">
                    @if (Model.CourseName != null)
            {
                        @Model.CourseName
                    }

                </th>
            </tr>
            <tr>

                <th>
                    @Html.DisplayName("LecNo.")
                </th>
                <th>
                    @Html.DisplayName("Semester")
                </th>
                <th>
                    @Html.DisplayName("1")
                </th>
                <th>
                    @Html.DisplayName("2")
                </th>
                <th>
                    @Html.DisplayName("3")
                </th>
                <th>
                    @Html.DisplayName("4")
                </th>
                <th>
                    @Html.DisplayName("5")
                </th>
                <th>
                    @Html.DisplayName("6")
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model._Timetablelistpivot)
            {
                <tr>

                    <td>
                        @Html.DisplayFor(modelItem => item.LecNo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Semester)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Monday)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Tuesday)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Wednesday)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Thursday)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Friday)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Saturday)
                    </td>
                </tr>

            }
        <tbody>
</table>
</div>

SchoolManagementSystems/Views/Timetable/publish.cshtml
@model Entity.timetableviewmodel
@{
    ViewBag.Title = "Publish Timetable";
    Layout = "~/Views/shared/_SharedLayout.cshtml";
}
<script type="text/javascript">
    $(document).ready(function () {
        $("#result").hide();
        FillPermission();
        $("#Send").click(function () {
            debugger;
            validations();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("SendTimetable")',
                data: $('#frm').serialize(),
                success: function (result) {
                    $("#lblmsg").text("Timetable link sent successfully!..");
                    $("#lblmsg").css({ "color": "lime" });
                    $("#lblmsg").css({ "font-size": "25px" });
                    $("#result").html(result);
                    clear();
                }
            });
        });
        $("#ViewTimetable").click(function () {
        validations();
            var course = $("#Classid option:selected").text();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("FillTimetable_classwise")',
                data: $('#frm').serialize() + "&CourseName=" + course + "",
                success: function (result) {
                    $("#result").html(result);
                    $("#result").show();
                }
            });
        });
        function validations() {
            var cnt = 0;

            if ($("#Classid").val() == '') {
                cnt++;
                $("#Classid").css({
                    "border": "2px solid red"
                });
            }
            else {
                $("#Classid").css({
                    "border": "",
                    "background": ""
                });
            }

            if (cnt != 0)
                e.preventDefault();
        }

      
    });
</script>
<script type="text/javascript">
    function printContent(el) {
           var panel = document.getElementById(el);
           var printWindow = window.open('', '', 'height=400,width=800');
           printWindow.document.write("<html> <head>");
           printWindow.document.write('</head><body><table>');
           printWindow.document.write(panel.innerHTML);
           printWindow.document.write('</table></body></html>');
           printWindow.document.close();
           setTimeout(function () {
               printWindow.print();
           }, 500);
           return true;
       }
</script>
@Html.Hidden("Add", ViewData["Add"])
@Html.Hidden("Modify", ViewData["Modify"])
@Html.Hidden("View", ViewData["View"])
@Html.Hidden("Delete", ViewData["Delete"])
<div class="container-fluid-full">
             
		<div class="row-fluid">
                @Html.Partial("_TimetableSubMenu")
	<div id="content" class="span10">
        	<div class="row-fluid">
              
                    <ul class="breadcrumb">
                     <li><i class="icon-home"></i>@Html.ActionLink("Home", "Login", "Login")<i class="icon-angle-right"></i>
                     @Html.ActionLink("Timetable Management", "Index", "Student", "")<i class="icon-angle-right"></i></li>
                        <li class="active">Publish Timetable</li>
                    </ul>

                   <div class="row-fluid sortable">
              <div class="box span12">
					<div class="box-header" data-original-title>
						<h2><i class="fa fa-edit"></i><span class="break"></span>Publish Time Table to Parents and Teacher</h2>
						<div class="box-icon">
						
							<a href="#" class="btn-minimize"><i class="fa fa-chevron-up" aria-hidden="true"></i></a>
						
						</div>
					</div>
                               		<div class="box-content">
						<form id="frm" class="form-horizontal">
                              
						
                                  <fieldset>
                            @using (Html.BeginForm("", "", FormMethod.Post, new { id = "frm", @class = "form-horizontal" }))
                            {
                                <div id="lblmsg"  class="control-group">
                                </div>
                                <div  class="control-group span5">
                                    @Html.LabelFor(model => model.Classid, new { @class = "control-label"  })
                                      <div class="controls"> 
                                          @Html.DropDownListFor(model => model.Classid, new SelectList(Model._CourseList, "id", "Course", "Select Course"), "Select Course", new { @for = "select" })
                                          @Html.ValidationMessageFor(model => model.Classid)
                                          </div>
                                </div>
                                <div class="control-group span5">
                                    <input type="button" class="btn-primary" id="ViewTimetable" value="ViewTimetable" />
                                   &nbsp;&nbsp;&nbsp;
                                    <input type="button" class="btn-primary" id="Print" onclick="printContent('result')" value="Print" />
                                    &nbsp;&nbsp;&nbsp;
                                    <input type="button" class="btn-primary" id="Send" value="Publish" />
                                    </div>
                                  

                                    }
</fieldset>
                                </form>
					
					</div>
				</div><!--/span-->
			
			</div><!--/row-->
                 <div class="row-fluid sortable">
              <div class="box span12">
                  	<div class="box-header" data-original-title>
						<h2><i class="fa fa-edit"></i><span class="break"></span>List View</h2>
						<div class="box-icon">
						
							<a href="#" class="btn-minimize"><i class="fa fa-chevron-up" aria-hidden="true"></i></a>
						
						</div>
					</div> 
                  <div class="box-content">
                        <div id="disptable">
                            <div class="" style="color: #23527c;">
                                @Html.Partial("_publishedtimetable")
                            </div>
                        </div>
                    </div>
                  </div>
                                             
                                                

                                         </div>
        </div>
             
    </div>
</div>
   
            </div>